Columns ordered in Containers CSV Export
c3g/freezeman_server pull request #127
Opened 2021-01-20 15:32 UTC by jleblond

It does work but I am not sure this is the best 'Django' way of doing it (overriding the get_renderer_context method which gets called because we use the CSV renderer from django_rest_framework_csv, and setting up a context columns 'header' if the action is list_export.... )

2021-01-20 15:48 UTC, UlysseFG reviewed
This seem to be a reasonable solution ... I would test for self.action before the assignment in case the header is set at some point and not set it in case its not list_export (your code would set it to None for anything but the list_export action which is not necessarily correct)

2021-01-21 19:08 UTC, UlysseFG reviewed
I'm not too sure why change "_name" to "_id" if the values retrieved are a name...

2021-01-21 19:12 UTC, jleblond commented
> I'm not too sure why change "_name" to "_id" if the values retrieved are a name...

Its per the user request to have the exact same names as in the Samples submission template

2021-01-21 20:00 UTC, UlysseFG commented
The exposed names should match but the internal names and logic do not need to be altered... The trouble we have here is that although the users use the name as ID we use id as ID. So if we start using a mix of both this will get messy fast. 
We can discuss this at the meeting, but my opinion is that we should not use the user's way to call stuff internally. The better option would be to actually change the individual, mother and father ID fields in the sample submission template to Name so we can all be on the same page. This would of course require a couple other changes in the sample submission ressource but it would straighten stuff up.

2021-01-21 20:44 UTC, jleblond commented
> The exposed names should match but the internal names and logic do not need to be altered... The trouble we have here is that although the users use the name as ID we use id as ID. So if we start using a mix of both this will get messy fast.
> We can discuss this at the meeting, but my opinion is that we should not use the user's way to call stuff internally. The better option would be to actually change the individual, mother and father ID fields in the sample submission template to Name so we can all be on the same page. This would of course require a couple other changes in the sample submission ressource but it would straighten stuff up.

Good idea to separate the internal names and the names used by the users. Another way of doing it would be to implement something that maps our internal names to the displayed names, such as a term dictionary.

2021-01-22 00:57 UTC, zxenia requested changes

2021-01-22 00:57 UTC, zxenia commented on fms_core/serializers.py
> +        return primitive_repr
I would advise against returning JSON where keys have whitespaces, it is prone to errors. You might use this endpoint for something else in the future and to deal with the whitespaces will be additional work.
It is enough that `get_renderer_context()` removes the ` _ ` in the header. So I suggest just remove `to_representation` methods, then the response at `/api/containers/list_export/` will be:
```
[
    {
        "name": "Freezer001",
        "container_kind": "freezer 3 shelves",
        "barcode": "Freezer001",
        "location": null,
        "coordinates": "",
        "comment": ""
    }
]
```
and the export at `/api/containers/list_export/?format_csv`  will return the csv with column names without underscore.

2021-01-22 00:57 UTC, zxenia commented on fms_core/serializers.py
> +        return primitive_repr
same as above

2021-01-22 01:16 UTC, zxenia commented
Hi @jleblond , @UlysseFG
I read your discussion on internal names and names for the user.
I agree that in the code we should only use internal names.
The user-expected naming should be in the things delivered directly to the user, e.g. UI or CSV column names.
Also because users may change the preference for the naming often.

2021-01-22 15:01 UTC, merged