Create sample creation date
c3g/freezeman_server pull request #130
Opened 2021-01-27 22:17 UTC by jleblond

NOTE: For review only. Not to be merged right now. 
Will be waiting for the release of 3.0.0, and then also make the required changes in the front-end as well.

2021-01-28 15:35 UTC, jleblond commented
> Quick comment ... There should be only one migration by release. If 11 was 3.0, 12 should be all of 3.1.

I need the data from the reception_date to fill the creation_date column, so the order of the migrations is important.

2021-01-28 16:12 UTC, davidlougheed commented
operations should be executed in order

2021-01-28 16:12 UTC, davidlougheed commented
sorry, misclick

2021-01-28 16:15 UTC, UlysseFG commented
Yeah as David mentioned each operation in a single migration is executed in order so you can just append your other migration operations after the ones in the previous migration.

2021-01-28 16:42 UTC, jleblond commented
Not from my tests, and from what I am finding on the Internet.. the order is not respected, therefore I get an error during the migration because the field reception_date does not exist

2021-01-28 16:55 UTC, UlysseFG commented
This is likely because the model you use to process the migration no longer has a reception_date in it. If you do the copying using an SQL query this should work. You can check in the previous migrations (0008_... for example). They include field copies that were made in a precise order.

2021-01-28 17:33 UTC, davidlougheed commented
I actually didn't mean to comment at all but I guess hit "close with comment" by accident with something I wasn't going to send in that form at least (sorry!)

There's also https://github.com/c3g/freezeman_server/blob/master/fms_core/migrations/0005_v2_0_0.py which did some field re-naming/shuffling stuff, not sure if anything I did there would be of help

2021-01-28 22:44 UTC, UlysseFG commented on fms_core/resources/sample.py
> +    creation_date = Field(attribute='creation_date', column_name='Creation Date', widget=DateWidget())
Je ne changerais pas le column_name ici (surtout si tu ne changes pas le column_name dans le template) Le user doit savoir qu'il soumet un reception date.

2021-01-28 22:49 UTC, UlysseFG commented on fms_core/migrations/0012_v3_1_0.py
> +        migrations.RenameField(
J'aime bien cette solution ; ) En passant, je ne sais pas si tu as d'autre changements qui vont s'ajouter, mais la creation d'un creation_date devrait inclure l'ajout d'une colonne dans le template (et la ressource) extraction pour ajouter un date_extracted. Faudrait confirmer avec David, mais l'ajout de samples a Freezeman ne se fait pas nécessairement la journée même d'une opération alors je permettrait que la date soit différente de la date courante de l'extraction dans freezeman...

2021-02-25 22:19 UTC, UlysseFG requested changes
This looks good, you have not renamed the samples versions fields from reception_date to creation_date.

2021-02-25 23:00 UTC, UlysseFG approved these changes
Looks good

2021-02-26 13:58 UTC, merged